// File generated by FlutterFire CLI (or manually populated placeholder).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRiBPfisp_Vz-CsGnYqrUqeB43NhyMBgc',
    appId: '1:377393188212:web:c5e1d442a8fbf9e78c7021',
    messagingSenderId: '377393188212',
    projectId: 'simpel-d86f7',
    authDomain: 'simpel-d86f7.firebaseapp.com',
    storageBucket: 'simpel-d86f7.firebasestorage.app',
    measurementId: 'G-4DBYZLW4SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDFen1IgTma2ZM-T3cTguqF8_ghuAtTAI',
    appId: '1:377393188212:android:4b2cf526bb095bd28c7021',
    messagingSenderId: '377393188212',
    projectId: 'simpel-d86f7',
    storageBucket: 'simpel-d86f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFHbkOeNNoIHZ3rhaWvJSmI_s3yZHUCyM',
    appId: '1:377393188212:ios:475b49948392b74f8c7021',
    messagingSenderId: '377393188212',
    projectId: 'simpel-d86f7',
    storageBucket: 'simpel-d86f7.firebasestorage.app',
    iosClientId: '377393188212-facbg33dsdoa1rvvjdlejsfdsfui9qid.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpel',
  );

}